# Generated by Django 3.2.16 on 2022-11-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_price_plan_feature_plan_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_plan',
            name='highlight_status',
        ),
        migrations.AddField(
            model_name='price_plan',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='price_plan',
            name='plan_img',
            field=models.ImageField(blank=True, upload_to='Plan Images', verbose_name='Plan Images'),
        ),
        migrations.DeleteModel(
            name='Price_plan_feature',
        ),
    ]
