# Generated by Django 3.2.16 on 2022-11-09 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_methods', '0003_auto_20221109_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_methods.price_plan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
