# Generated by Django 3.2.16 on 2022-12-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0004_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_plan',
            name='perline_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
