# Generated by Django 3.2.16 on 2022-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0006_alter_price_plan_perline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='stripeCustomerId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer Id'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Subscription Id'),
        ),
    ]
