# Generated by Django 3.2.16 on 2023-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0007_auto_20221225_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_plan',
            name='api_keys',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
