# Generated by Django 3.2.16 on 2023-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_landing_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Mail'), ('2', 'Femail')], max_length=25, null=True, verbose_name='Gender'),
        ),
    ]
