# Generated by Django 3.2.16 on 2023-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_lifetime',
            field=models.BooleanField(default=False),
        ),
    ]
