# Generated by Django 3.2.16 on 2022-11-09 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_alter_wallet_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=2000, null=True)),
                ('country', models.CharField(blank=True, max_length=2000, null=True)),
                ('no_of_records_limit', models.IntegerField(blank=True, null=True)),
                ('locations', models.CharField(blank=True, max_length=2000, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='scrapped_files', verbose_name='Scrapped Files')),
                ('inserted_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
