# Generated by Django 3.2.16 on 2022-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_wallet_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_query',
            name='output_file',
            field=models.FileField(blank=True, max_length=25000, null=True, upload_to='scrapped_files', verbose_name='Scrapped Files'),
        ),
    ]
