# Generated by Django 3.2.16 on 2022-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_user_query_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_query',
            name='query_type',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
