# Generated by Django 3.2.16 on 2022-12-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_user_query_query_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
