# Generated by Django 3.2.16 on 2022-12-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_user_query_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_query',
            name='query_list',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
    ]
