# Generated by Django 3.2.16 on 2023-06-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
